// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RingoMediaProject.DataContext;

#nullable disable

namespace RingoMediaProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241208171003_Initial Migration for department")]
    partial class InitialMigrationfordepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RingoMediaProject.DomainModel.Models.Department", b =>
                {
                    b.Property<int>("Dept_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dept_Id"));

                    b.Property<int?>("DepartmentsDept_Id")
                        .HasColumnType("int");

                    b.Property<string>("Dept_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Dept_Parent_Id")
                        .HasColumnType("int");

                    b.HasKey("Dept_Id");

                    b.HasIndex("DepartmentsDept_Id");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("RingoMediaProject.DomainModel.Models.Department", b =>
                {
                    b.HasOne("RingoMediaProject.DomainModel.Models.Department", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartmentsDept_Id");

                    b.Navigation("Departments");
                });
#pragma warning restore 612, 618
        }
    }
}
